### ISSUE TITLE
Doesn't render if compiled with GCC-13

### ISSUE THREAD

**Issue by thoughton** [floooh/pacman.c#11] opened 2023-11-11 15:57 UTC
Hi, any thoughts why this doesn't work with GCC-13 (current stable GCC release)?
It builds fine, and when running it the window appears, but no visuals ever render, and no input is ever accepted.
I noticed the problem after both updating my laptop to Ubuntu 23.10, and also updating my Windows PC's msys2.
Instructing cmake to use GCC-12 instead on the laptop solves the issue. (Haven't tried the same on Windows.)

**Comment by floooh** [comment] 2023-11-12 14:42
Hmm no idea, I'll need to check. Clang's static analyzer, address saniziter and undefined behaviour sanitizer are all clean, so it's unlikely that it's some subtle memory corruption or UB problem. I'll try to look into it over the next few days.

**Comment by floooh** [comment] 2023-11-12 16:11
I've upgraded to Ubuntu 23.04 now, but this gives me gcc 12.3.0 by default. Did you install gcc13 manually?

**Comment by floooh** [comment] 2023-11-12 16:29
Ok I can confirm the problem. Installing gcc-13 gives me version 13.0.1 though which is still marked as experimental.

But yeah, pacman.c renders a black screen. Thankfully my other code (sokol-samples, chips emulators and visual6502remix) all seem to be working. I'll start investigating.

**Comment by floooh** [comment] 2023-11-12 17:02
Found the issue and will provide a fix shortly. Basically this while-loop is never entered because `TICK_TOLERANCE_NS` is an enum item with an unsigned-integer backing type (I guess because there's an 0xFFFFFFFF in the same enum).

https://github.com/floooh/pacman.c/blob/cebded88be312ead07ab85d6dc02e309f7cddedb/pacman.c#L739

Really ugly issue, but tbf with -Wall -Wextra the compiler warns about comparison with different signs. I'll clean up those warnings, which should also fix the issue.

I wonder how much other code out there will break because of this gcc behaviour change.

**Comment by floooh** [comment] 2023-11-12 17:40
Ok, fixed in https://github.com/floooh/pacman.c/commit/10df76ff2a0b68d17540b17117ac612eae67e3bf. Thanks for the bug report!

I still wonder though if gcc13 is "in the right" here :) (because enabling `-Wall -Wextra -Wsign-compare` doesn't warn about signed/unsigned comparison in Clang, so I guess that Clang doesn't convert that enum to an unsigned-int underlying type).

**Closed as completed by floooh** 2023-11-12 17:40 UTC

**Comment by thoughton** [comment] 2023-11-12 21:22
Woah, that is a gnarly cause! Thanks a lot for the quick fix and the detailed explanation.

I too wonder if this gcc change could be causing other issues out in the wild... Kinda scary tbh.

By the way, the issue was present for me in gcc13.2, which I'm assuming is classed as a "stable" release as it is what is included in Ubuntu 23.10 by default (confirmed here: https://discourse.ubuntu.com/t/mantic-minotaur-release-notes/35534#toolchain-upgrades-8).

Thanks again!
